In [2]:
import numpy as np


In [22]:
a = np.array((1,2,3)) # we can use list or tuple inside creation of array

In [27]:
print(a)

[1 2 3]


In [39]:
b = np.array([[1,2],[2,3]])

In [40]:
print(b)

[[1 2]
 [2 3]]


In [44]:
c = np.array([[1,2],[2,3]],dtype = 'complex') #float in place of data type
print(c)

[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]]


In [46]:
help(np.array([]))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [52]:
d = np.array((10,'float')

In [53]:
print(d)

10.0


In [50]:
print(type(d))

<class 'list'>


In [62]:
# arrange
np.arange(1,9,2,dtype='float')

array([1., 3., 5., 7.])

In [3]:
# zeros
np.zeros(5) # defalut type is float

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(2,dtype='int')

array([0, 0])

In [6]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [4]:
# ones
np.ones([3,2],dtype = 'complex')

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [5]:
#empty
np.empty(3)

array([ 4.22788818e-307,  1.01942430e-311, -0.00000000e+000])

In [6]:
np.empty([3,2],'int')

array([[    4980804,     5439561],
       [ 1753442640,         480],
       [          0, -2147483648]])

In [7]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [21]:
np.linspace(1,500,dtype = 'float',num = 10,retstep = True)

(array([  1.        ,  56.44444444, 111.88888889, 167.33333333,
        222.77777778, 278.22222222, 333.66666667, 389.11111111,
        444.55555556, 500.        ]),
 55.44444444444444)

In [22]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

In [41]:
# eye
np.eye(N =3,M =3,k = -1,dtype=int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [48]:
# identity
np.identity(n = 5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [49]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.

In [63]:
# random
np.random.randint([10,5])



array([3, 4])

In [4]:
print(np.random.rand(10,2))
np.random.rand(2,5,2)

[[0.67575541 0.52863527]
 [0.31152662 0.47208453]
 [0.86710291 0.94648885]
 [0.13242638 0.07598027]
 [0.61677285 0.37080224]
 [0.59333348 0.36822831]
 [0.58039295 0.9152788 ]
 [0.13589808 0.74860811]
 [0.0081082  0.59025715]
 [0.68684786 0.7541959 ]]


array([[[0.04647089, 0.57222609],
        [0.98339343, 0.73702137],
        [0.70050739, 0.70419099],
        [0.69972649, 0.8270011 ],
        [0.94492892, 0.95457278]],

       [[0.67649514, 0.69123321],
        [0.94918672, 0.25057611],
        [0.60459886, 0.00782883],
        [0.7409132 , 0.83004376],
        [0.34080431, 0.9058763 ]]])

In [74]:
np.random.randn(5,10,2)

array([[[-0.3301632 , -0.11705631],
        [-0.26934107,  2.01164277],
        [-0.55638391,  0.52597637],
        [-0.01446803, -1.29037309],
        [-0.0234015 , -1.90812596],
        [-0.94278682, -0.2346156 ],
        [-0.96652404, -0.83687937],
        [ 0.19127424,  0.71439033],
        [ 0.72997426,  1.27138989],
        [-1.19993015,  0.84077166]],

       [[ 0.32413078, -0.1556179 ],
        [ 1.81686079,  1.21768365],
        [ 1.8375719 , -0.41005383],
        [-1.16533607,  0.3256809 ],
        [-2.15542765,  0.74644974],
        [ 0.12546025, -1.29730433],
        [ 0.52249346, -0.25206318],
        [ 1.19989337, -0.42718772],
        [ 0.95389261, -0.12115083],
        [ 0.9382509 ,  0.79055847]],

       [[-0.27365668,  1.76817081],
        [ 0.13773441,  1.3739244 ],
        [ 0.20442089,  1.0345608 ],
        [ 0.31940714, -1.37589099],
        [ 0.13168065, -1.05081213],
        [-0.27487192,  0.98571043],
        [-0.88221598,  0.95091711],
        [-1.42583895, -1

In [78]:
np.random.ranf((10,2))

array([[0.21142323, 0.88033602],
       [0.92495483, 0.55627385],
       [0.68995645, 0.08998744],
       [0.73860474, 0.97354803],
       [0.76524314, 0.32742156],
       [0.42880062, 0.57515544],
       [0.12585766, 0.45073005],
       [0.39550022, 0.49523314],
       [0.78657938, 0.23775394],
       [0.51471559, 0.38319524]])

In [83]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [105]:
np.random.randint(0,25,size = (2,3,2,2),dtype = 'int')

array([[[[15,  9],
         [22, 11]],

        [[16,  7],
         [ 2,  5]],

        [[ 4, 17],
         [13,  2]]],


       [[[18,  4],
         [15, 18]],

        [[ 1, 10],
         [16, 16]],

        [[24,  1],
         [ 4,  1]]]])

In [129]:
a = np.array(([1,2,3],[4,5,6]),dtype = 'int')

In [130]:
a.ndim

2

In [115]:
help(np.ndim)

Help on function ndim in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



In [117]:
a.shape

(2, 3)

In [120]:
a.size

6

In [126]:
a.dtype

dtype('float64')

In [127]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [131]:
a.itemsize

4

In [6]:
# numpy data types

b = np.zeros(5)
b.dtype

dtype('float64')

In [15]:
b = np.zeros(5,np.int16)
b.dtype

dtype('int16')

In [18]:
# datatypes can be used as a functions

x = np.int64(2)
x.dtype

dtype('int64')

In [20]:
x = np.float32(1)
x.dtype

dtype('float32')

In [41]:
# datatype can be reffered by charecter

a = np.zeros(3,dtype = 'i')
a

array([0, 0, 0], dtype=int32)

In [75]:
#after array creation how to change the data type of an array we should use temporary variable to store it.

b = np.zeros(2)
print(b.dtype)
print(b.astype(np.int64).dtype)

  #OR
z = b.astype(int)
z.dtype



float64
int64


dtype('int32')

In [58]:
help(b.astype(int))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [77]:
# dimensions array acess

a = np.array([1,2,3]) # 1d
print(a[0])
print(a[-3]) # both indexing like o or -3 both are pointing to value 1

1
1


In [83]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[1][0]

4

In [132]:
b = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [13,14,15],
    [16,17,18]]
])
b[1][1][1]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [112]:
# array slicing
a = np.array([1,2,3,4,5,6]) # 1 - d

a[::3]

array([1, 4])

In [113]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [114]:
b[1:,::2]

array([[4, 6],
       [7, 9]])

In [137]:
# 3d operation slcing
    
c = np.array([[[30,40,50,60],
      [90,80,110,65],
      [125,95,78,45],
      [78,98,66,74]],
     
     [[12,13,15,18],
      [78,45,65,31],
      [88,98,56,54],
      [4,8,12,16]
     ]])
c[1:,2:,3:]   


array([[[54],
        [16]]])

In [139]:
c[:,:,::3] # start:end:step-->this is for each i,j and k

array([[[ 30,  60],
        [ 90,  65],
        [125,  45],
        [ 78,  74]],

       [[ 12,  18],
        [ 78,  31],
        [ 88,  54],
        [  4,  16]]])

In [17]:
# arthmetic operation using numpy array

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print(a+2)
    # OR
print(np.add(a,2))
print(np.subtract(a,2))
print(np.multiply(a,2))
print(np.divide(a,2))
print(np.mod(a,2))
print(np.power(a,2))

[3 4 5 6 7]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]
[ 1  4  9 16 25]


In [19]:
print(np.add(a,b))
print(np.multiply(a,b))

[ 5  7  9 11 13]
[ 4 10 18 28 40]


In [25]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,12,14],[13,18,17]])

print(a+2)

[[3 4 5]
 [6 7 8]]


In [26]:
print(a+b)

[[11 14 17]
 [17 23 23]]


In [32]:
# broadcasting

a = np.array([1,2,3])
b = np.array([1,2,3,4])

print(b.shape(0))

#print(a*b)

TypeError: 'tuple' object is not callable

In [39]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print(np.shape(a))
print(np.shape(b))
print(a+b)

(2, 3)
(2, 3)
[[ 2  4  6]
 [ 8 10 12]]


In [59]:
# reshape without affecting the data

a = [1,2,3,4,5,6]
b = np.reshape(a,(3,2),order = 'f') # column wise operation
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
a = np.array([[1,2,3],[4,5,6]])
b = np.reshape(a,(2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
# similar to reshape
a = np.array([[1,2,3],[4,5,6]])
a.reshape((3,2))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
# resize

a = np.array([1,2,3,4,5])

b = np.resize(a,(4,3))
print(b)


[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]


In [80]:
a = np.array([1,2,3,4,5]) # using this function it will permenently change the original darray size
a.resize((4,4))
a

array([[1, 2, 3, 4],
       [5, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
# flatten and ravel array

a = np.array([[[1,2,3],
      [4,5,6]],
     
     [[7,8,9],
      [10,11,12]]])

a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [93]:
print(a.ravel())
# OR
print(np.ravel(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
# transpose

a = np.array([[[1,2,3,4],
      [4,5,6,7],
      [30,40,50,60]],
     
     [[7,8,9,10],
      [10,11,12,15],
     [65,75,85,95]]])
print(a.shape)
print(np.transpose(a).shape)
np.transpose(a)


(2, 3, 4)
(4, 3, 2)


array([[[ 1,  7],
        [ 4, 10],
        [30, 65]],

       [[ 2,  8],
        [ 5, 11],
        [40, 75]],

       [[ 3,  9],
        [ 6, 12],
        [50, 85]],

       [[ 4, 10],
        [ 7, 15],
        [60, 95]]])

In [6]:
np.transpose(a,axes = (1,0,2))

array([[[ 1,  2,  3,  4],
        [ 7,  8,  9, 10]],

       [[ 4,  5,  6,  7],
        [10, 11, 12, 15]],

       [[30, 40, 50, 60],
        [65, 75, 85, 95]]])

In [7]:
# one more method for transpose

a.transpose()

array([[[ 1,  7],
        [ 4, 10],
        [30, 65]],

       [[ 2,  8],
        [ 5, 11],
        [40, 75]],

       [[ 3,  9],
        [ 6, 12],
        [50, 85]],

       [[ 4, 10],
        [ 7, 15],
        [60, 95]]])

In [12]:
a = np.array([[[1,2,3,21],
               [4,5,6,22],
               [7,8,9,23]],
              
              [[10,11,12,24],
               [13,14,15,25],
               [16,17,18,26]]])

In [13]:
np.transpose(a,axes = (1,0,2))

array([[[ 1,  2,  3, 21],
        [10, 11, 12, 24]],

       [[ 4,  5,  6, 22],
        [13, 14, 15, 25]],

       [[ 7,  8,  9, 23],
        [16, 17, 18, 26]]])

In [15]:
# swapaxes
help(np.swapaxes)

Help on function swapaxes in module numpy:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier NumPy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    array([[1],
           [2],
           [3]])
    
    >>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    >>> x
    array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
    
    >>> np.swapaxes(x,0,2)
    array([[[0, 4],
            [2, 6]],
           [[1, 5],
            [3, 7]]])



In [16]:
np.swapaxes(a,1,2)

array([[[ 1,  4,  7],
        [ 2,  5,  8],
        [ 3,  6,  9],
        [21, 22, 23]],

       [[10, 13, 16],
        [11, 14, 17],
        [12, 15, 18],
        [24, 25, 26]]])

In [47]:
# concatenate
a = np.array([1,2,3])
c = np.zeros(9,dtype = int)
b = np.arange(4,10)
print(np.concatenate((a,b),out = c))
print(c)


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [59]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11,12],[13,45,50]])
np.concatenate((a,b),(1))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 45, 50]])

In [81]:
# vstack
a = np.arange(5)
b = np.arange(5,10) # if 10 is become 11 or any no it throws an error
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11,12]])
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [77]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis

In [84]:
# hstack
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,11,12],[13,45,50]])
np.hstack((a,b))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 45, 50]])

In [85]:
a = np.array([1,2,3])
b = np.arange(4,10)
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis.
    s

In [100]:
# split

a =np.arange(10)
np.split(a,2)


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [129]:
b = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(b,2,axis = 0))
np.split(b,2,axis = 1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [127]:
np.vsplit(b,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [130]:
np.hsplit(b,2)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [133]:
# insert
a = np.array([1,2,3,4])
print(np.insert(a,2,25))
np.insert(a,(2,4),45)

[ 1  2 25  3  4]


array([ 1,  2, 45,  3,  4, 45])

In [155]:
b = np.array([[1,2,3],
              [3,4,5]])
np.insert(b,1,55,None)

array([ 1, 55,  2,  3,  3,  4,  5])

In [156]:
np.insert(b,1,55,0)


array([[ 1,  2,  3],
       [55, 55, 55],
       [ 3,  4,  5]])

In [159]:
np.insert(b,1,[55,65,75],0)

array([[ 1,  2,  3],
       [55, 65, 75],
       [ 3,  4,  5]])

In [165]:
np.insert(b,1,[55,],1)

array([[ 1, 55,  2,  3],
       [ 3, 55,  4,  5]])

In [166]:
np.insert(b,1,[55,5],1)

array([[ 1, 55,  2,  3],
       [ 3,  5,  4,  5]])

In [170]:
# append
np.append(a,25)
b

array([[1, 2, 3],
       [3, 4, 5]])

In [197]:
np.append(b,[[42],[43]],axis = 1)

array([[ 1,  2,  3, 42],
       [ 3,  4,  5, 43]])

In [213]:
np.append(b,23,axis = 0) # it is not possible because b is 2d array

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [215]:
# delete
np.delete(a,2)

array([1, 2, 4])

In [225]:
np.delete(b,1,0)


array([[1, 2, 3]])

In [226]:
np.delete(b,1,1)

array([[1, 3],
       [3, 5]])

In [2]:
# matrix

# matrix adition which is same as array adition
a = np.array([[1,2,3],
     [10,20,30],
     [4,5,6]])

b = np.array([[7,8,9],
     [20,40,60],
     [5,6,7]])

a+b

array([[ 8, 10, 12],
       [30, 60, 90],
       [ 9, 11, 13]])

In [3]:
# matrx multiplication
a.dot(b)

array([[  62,  106,  150],
       [ 620, 1060, 1500],
       [ 158,  268,  378]])

In [4]:
np.dot(a,b) 

array([[  62,  106,  150],
       [ 620, 1060, 1500],
       [ 158,  268,  378]])

In [16]:
# creation of matrix intead of using array

a =np.matrix("1,2;4,5",dtype =float) # 1 method of matrix creation

b =np.matrix([[10,20],[40,50]],dtype =float) # another method


In [18]:
# matrix addion 
a+b

matrix([[11., 22.],
        [44., 55.]])

In [20]:
# matrix multiplication
c =a*b
c

matrix([[ 90., 120.],
        [240., 330.]])

In [21]:
c.T

matrix([[ 90., 240.],
        [120., 330.]])

In [24]:
# matrix power 
a =np.matrix("1,2;4,5",dtype =int)
print(a)
np.linalg.matrix_power(a,2)

[[1 2]
 [4 5]]


matrix([[ 9, 12],
        [24, 33]])

In [25]:
np.linalg.matrix_power(a,0)

matrix([[1, 0],
        [0, 1]])

In [26]:
np.linalg.matrix_power(a,-2)

matrix([[ 3.66666667, -1.33333333],
        [-2.66666667,  1.        ]])

In [28]:
# invres matrix
c = np.linalg.inv(a)

matrix([[-1.66666667,  0.66666667],
        [ 1.33333333, -0.33333333]])

In [31]:
np.linalg.matrix_power(c,2)

matrix([[ 36900.,  50400.],
        [100800., 137700.]])

In [32]:
# linear equation
a = np.array([[3,1],[1,2]]) # 3x+y,x+2y
b = np.array([9,8]) # 3x+y = 9, x+2y = 8

np.linalg.solve(a,b)

array([2., 3.])

In [34]:
a = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
b = np.array([13,13,26])

np.linalg.solve(a,b)

array([2., 3., 1.])